name: "Bump Version"

on:
  push:
    branches:
      - "dev"
jobs:
  bump-version:
    name: "Bump Version on dev"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - id: create_token
        name: GitHub App token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: "${{ secrets.AUTOMATIC_BUMP_APP_ID }}"
          private_key: "${{ secrets.AUTOMATIC_BUMP_APP_PRIVATE_KEY }}"
      - name: "Checkout source code"
        uses: "actions/checkout@v4"
      - name: "Automated Version Bump"
        id: version-bump
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ steps.create_token.outputs.token }}
        with:
          skip-tag: "true"
          skip-push: "true"
          commit-message: "chore: Bump to v{{version}}"
      - name: "Create Pull Request"
        uses: peter-evans/create-pull-request@v3
